### ISSUE TITLE
build:json fails on windows

### ISSUE THREAD

**Issue by michelmueller** [adobe-rnd/aem-boilerplate-xwalk#45]
executing build:json fails on windows

### ubuntu (OK)
```
npm run build:json

> @adobe/aem-boilerplate@1.3.0 build:json
> npm-run-all -p build:json:models build:json:definitions build:json:filters


> @adobe/aem-boilerplate@1.3.0 build:json:models
> merge-json-cli -i 'models/_component-models.json' -o 'component-models.json'


> @adobe/aem-boilerplate@1.3.0 build:json:filters
> merge-json-cli -i 'models/_component-filters.json' -o 'component-filters.json'


> @adobe/aem-boilerplate@1.3.0 build:json:definitions
> merge-json-cli -i 'models/_component-definition.json' -o 'component-definition.json'

writing component-models.json...
writing component-definition.json...
writing component-filters.json...
```

### windows
```
npm run build:json                                          

> @adobe/aem-boilerplate@1.3.0 build:json
> npm-run-all -p build:json:models build:json:definitions build:json:filters


> @adobe/aem-boilerplate@1.3.0 build:json:definitions
> merge-json-cli -i 'models/_component-definition.json' -o 'component-definition.json'


> @adobe/aem-boilerplate@1.3.0 build:json:filters
> merge-json-cli -i 'models/_component-filters.json' -o 'component-filters.json'


> @adobe/aem-boilerplate@1.3.0 build:json:models
> merge-json-cli -i 'models/_component-models.json' -o 'component-models.json'

node:internal/fs/promises:639
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'C:\mmsoft\dev\aem-boilerplate-xwalk\'models\_component-definition.json''
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async readJsonFile (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:7:23)
    at async merge (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:124:28)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:58:29
    at async Promise.all (index 0)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:54:1 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: "C:\\mmsoft\\dev\\aem-boilerplate-xwalk\\'models\\_component-definition.json'"
}
node:internal/fs/promises:639
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'C:\mmsoft\dev\aem-boilerplate-xwalk\'models\_component-models.json''
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async readJsonFile (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:7:23)
    at async merge (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:124:28)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:58:29
    at async Promise.all (index 0)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:54:1 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: "C:\\mmsoft\\dev\\aem-boilerplate-xwalk\\'models\\_component-models.json'"
}
node:internal/fs/promises:639
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'C:\mmsoft\dev\aem-boilerplate-xwalk\'models\_component-filters.json''
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async readJsonFile (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:7:23)
    at async merge (file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/merge.js:124:28)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:58:29
    at async Promise.all (index 0)
    at async file:///C:/mmsoft/dev/aem-boilerplate-xwalk/node_modules/merge-json-cli/src/cli.js:54:1 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: "C:\\mmsoft\\dev\\aem-boilerplate-xwalk\\'models\\_component-filters.json'"
}

Node.js v20.16.0

Node.js v20.16.0

Node.js v20.16.0
ERROR: "build:json:definitions" exited with 1.

```

**Comment by buuhuu** [comment]
Thanks @michelmueller for your contribution, merged.
